# Generated by Django 4.2.6 on 2024-02-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='', verbose_name='About/img')),
                ('img2', models.ImageField(upload_to='', verbose_name='About/img')),
                ('img3', models.ImageField(upload_to='', verbose_name='About/img')),
                ('img4', models.ImageField(upload_to='', verbose_name='About/img')),
            ],
        ),
    ]
