# Generated by Django 4.2.6 on 2024-02-23 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='Aboutus/img')),
            ],
        ),
        migrations.CreateModel(
            name='Categoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('teacher', models.CharField(max_length=100)),
                ('soat', models.IntegerField()),
                ('pupil', models.IntegerField()),
                ('img', models.ImageField(upload_to='Course/img')),
            ],
        ),
        migrations.CreateModel(
            name='Itcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='Itcourse/img')),
                ('time', models.TimeField()),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ittopbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='Ittopbar/img')),
            ],
        ),
        migrations.CreateModel(
            name='Kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='Kids/img')),
                ('time', models.TimeField()),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teamtopbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='Teamtopbar/img')),
                ('bio2', models.TextField()),
                ('img2', models.ImageField(upload_to='Teamtopbar/img2')),
            ],
        ),
        migrations.CreateModel(
            name='Pupils5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Pupil/img')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Pupils4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Pupil/img')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Pupils3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Pupil/img')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Pupils2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Pupil/img')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoriya')),
            ],
        ),
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Pupil/img')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categoriya')),
            ],
        ),
    ]
